apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyzer
  template:
    metadata:
      labels:
        app: analyzer
    spec:
      containers:
        - name: analyzer
          image: mwkido/analyzer:latest
          ports:
            - containerPort: 5750
---
apiVersion: v1
kind: Service
metadata:
  name: analyzer-service
spec:
  selector:
    app: analyzer
  ports:
    - protocol: TCP
      port: 5750
      targetPort: 5750
  type: LoadBalancer