apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-generator
  template:
    metadata:
      labels:
        app: report-generator
    spec:
      containers:
        - name: report-generator
          image: mwkido/report_generator:latest
          ports:
            - containerPort: 5500
---
apiVersion: v1
kind: Service
metadata:
  name: report-generator-service
spec:
  selector:
    app: report-generator
  ports:
    - protocol: TCP
      port: 5500
      targetPort: 5500
  type: LoadBalancer